### ISSUE TITLE
Broken interaction with updated Bootstrap Wrapper

### ISSUE THREAD

**Issue by suedunham** [gturri/nspages#106]
I'm not sure there's anything to be done to this plugin, but I haven't gotten any nibbles [at the other plugin's site](https://github.com/giterlizzi/dokuwiki-plugin-bootswrapper/issues/122), so I'll mention it here as well. I was using nspages with the `‑simpleList` option to fill navigational pills in Bootstrap Wrapper. A recent update to that plugin broke that functionality, and the dropdown list is now empty. Changing the code to use `‑simpleLineBreak` is a workaround for now, but the list is not formatted the right way.

I don't know if this is his problem, your problem, or my problem :) I'm using the most current versions of both plugins and dokuwiki with chrome. No javascript errors are showing up in the console, but I am having trouble getting IIS to show anything on the php side (php version 7.4).

I do know that Hogfather and Bootstrap3 weren't working well together (including issues with menus) until both had been upgraded to use jquery 3.5.1. That sort of thing is way over my head and may be irrelevant here, but I'll mention it.

**Comment by gturri** [comment]
I'm afraid I don't know this other plugin, so I don't know either in which bug is the bug you're looking for.
All I can say is that nspages doesn't rely on javascript at all (the content is completely computed server-side), so it's pretty normal (as far as nspages is concerned) that there are no JS error in the console

**Comment by gturri** [comment]
I'm closing this issue since there isn't enough information to make sure this issue comes from nspages.
(Feel free to re-open if you can provide more information)
