### ISSUE TITLE
customTitle option not working

### ISSUE THREAD

**Issue by Openuser87** [gturri/nspages#115]
Input (copied from plugin page)
`<nspages -customTitle="[{date.created}] {title} by {user}">`

yields an error:
`This namespace does not exist: -customTitle="[{date.created}] {title} by {user}" `

**Comment by gturri** [comment]
Hi,
This option has been added quite recently (with version `2021-02-16`). If you have an older version of nspages you should update it. Otherwise I would need more information because I'm not able to reproduce this issue

**Comment by Openuser87** [comment]
Hi Guillaume,

yes, it was due to the update! Everything works now. Thanks so much, great answer speed!
