### ISSUE TITLE
Warning on line 299

### ISSUE THREAD

**Issue by ics01** [gturri/nspages#118]
Hello @gturri 

I experienced a problem using the following line : 

<nspages wiki:documents:reunions -nbCol=2 -textPages="" -h1 -r -simpleLineBreak -customTitle="[{date.created}] {title} - Auteur : {user}" >

The programme answer :

Warning: preg_split() expects parameter 2 to be string, array given in /home/www/extranet/inc/parserutils.php on line 299

Warning: Invalid argument supplied for foreach() in /home/www/extranet/inc/parserutils.php on line 299

Warning: preg_split() expects parameter 2 to be string, array given in /home/www/extranet/inc/parserutils.php on line 299

Warning: Invalid argument supplied for foreach() in /home/www/extranet/inc/parserutils.php on line 299

If you have any idea ?
Merci beaucoup !

**Comment by gturri** [comment]
Thanks for this bug report. I just made a fix, available in version 2021-06-19.

**Comment by ics01** [comment]
Thank you very much, @gturri, it works perfectly.

Congratulation for the jog, and the quality and quickness of the answer.
