### ISSUE TITLE
Fatal error - deprecated PHP syntax in printerNice.php on line 97

### ISSUE THREAD

**Issue by SabineSW** [gturri/nspages#119]
Hi,

after an upgrade of PHP from 8.0.9 to 8.0.11 dokuwiki (hogfahter) displays blank pages.

In /var/log/apache2/error.log:
Got error 'PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /data/httpd/wiki/lib/plugins/nspages/printers/printerNice.php on line 97'

In the private function _uniord($c) the curly braces {} should be replaced with square brackets [].

nspages is not the only plugin affected...

**Comment by gturri** [comment]
Thanks for this detailed bug report. I'll try to take the time to apply,
test, and release the fix in the next few days.
