### ISSUE TITLE
"-exclude" excludes more than just current page

### ISSUE THREAD

**Issue by vic-t** [gturri/nspages#125]
Here is the nspages instruction I'm using: 

`<nspages kb:apps: -simpleList -r=3 -h1 -pregPagesOn="/start/i" -textPages="" -exclude>`

What I'm trying to do is to show the title of each starting page of a sub namespace, called "start", excluding the page I'm currently in. 

Specifically, the instruction above has been created on `kb:apps:start`. Let's say I have the following two sub namespaces `kb:apps:app1:` and `kb:apps:app2:`, they both have a `start` page plus many other pages. I only wish to see their starting page in the list. 

This works if I remove `-exclude` from the instruction above but then I will also see the title of `kb:apps:start` in the list. If I leave -exclude in the instruction, in the hopes of not seeing this one page, I get the info that there are _no pages in this namespace_.

**Comment by vic-t** [comment]
By the way, this is on 2020-07-29 "Hogfather" with nspages 2022-07-13

**Comment by gturri** [comment]
Thanks for this bug report. I can totally reproduce this issue.
However I'm afraid the fix may be a bit tricky and I will likely not have a lot of time to work on that any time soon... :-/
In the meantime, perhaps a workaround could be to set a custom title to the page you want to exclude and then to use the `-pregPagesTitleOff` option...

**Comment by gturri** [comment]
It's fixed. You can update to the latest version of the plugin ("2022-08-09").
(you may need to empty the cache of your browser and the cache of Dokuwiki to see the fix in action)

**Comment by vic-t** [comment]
Hey, wow, I didn't expect this to happen so soon. Thanks a lot. It works by the way, I already tested it.
