### ISSUE TITLE
Error While Listing, double list, when "start" exist.

### ISSUE THREAD

**Issue by Damodara1687** [gturri/nspages#142]
Hello,

wehn i try to list the Entire wiki, then the start page exist double, 1 times as the folder itself, and 1 Times in the folder with same name, is there a way to prevent this?

Using this in my Sidebar:
`<nspages : -tree -r -exclude -subns -pagesInNs -h1 -textPages="" -hideNoPages -textNS="" -exclude:daybook_sites: -exclude:playground: -exclude:struct: -exclude:wiki:>`

**Comment by gturri** [comment]
I'm afraid it's because of how Dokuwiki represents namespaces (I guess you observe the same behavior for all subnamespaces, doesn't it?)
I think you could add `-exclude:start:` (in order to keep only the 1 occurence which represents the page).
Does that work?
