### ISSUE TITLE
Uninitialized string offset in optionParser.php on line 126

### ISSUE THREAD

**Issue by dregad** [gturri/nspages#143]
The following tag  is throwing a warning:

> Warning: Uninitialized string offset -1 in .../dokuwiki/nspages/optionParser.php on line 126

```
<nspages -r -title -sortByDate -reverse -numberedList -nbItemsMax=10 -textPages="" -exclude:wiki: -exclude:[start wiki: syntax ]>
```

PHP 8.2, DokuWiki Jack Jackrum, nspages 2023-02-28

Backtrace

```
#0 .../lib/plugins/nspages/optionParser.php(126): dokuwiki\ErrorHandler::errorHandler(2, 'Uninitialized s...', '.../w...', 126)
#1 .../lib/plugins/nspages/optionParser.php(93): optionParser::_addListOfItemsToExclude(Array, Array, Array)
#2 .../lib/plugins/nspages/syntax.php(88): optionParser::checkExclude(' -exclud...', Array, Array, false)
#3 .../inc/parser/handler.php(284): syntax_plugin_nspages->handle(' -exclud...', 5, 530, Object(Doku_Handler))
#4 .../inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('<nspages -r -ti...', 5, 530, 'nspages')
#5 .../inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('<nspages -r -ti...', 5, 530)
#6 .../inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '<nspages -r -ti...', '_plugin_nspages', 530, 530)
#7 .../inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\n\n===== Cr\xC3\xA9at...')
#8 .../inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n====== Bienven...')
#9 .../inc/parserutils.php(198): p_get_instructions('====== Bienvenu...')
#10 .../inc/parserutils.php(525): p_cached_instructions('/Users/dregad/w...', false, 'start')
#11 .../inc/parserutils.php(299): p_render_metadata('start', Array)
#12 .../inc/common.php(266): p_get_metadata('start')
#13 .../doku.php(97): pageinfo()
#14 {main}
```

**Comment by gturri** [comment]
Thanks for this bug report.

I'll try to come up with a fix. In the meantime you can avoid this issue by turning `-exclude:[start wiki: syntax ]` into `-exclude:[start wiki: syntax]` (ie: remove the whitespace near the end).

**Comment by gturri** [comment]
Turns out the fix was not too complex, I've just pushed it. You can update nspages to the version I just pushed ("2023-04-19") to get this fix.

**Comment by desbest** [comment]
I've just upgraded the plugin just now and it actually works,
Beforehand the plugin was so faulty it was unusable but at least now I can finally use it.
Thank you for the bug fix.

**Comment by dregad** [comment]
> Beforehand the plugin was so faulty it was unusable

I don't think it's fair to say the plugin was *unusable* - after all it was just a WARNING which can easily be squelched by adapting php.ini settings.
