### ISSUE TITLE
Deprecated DokuWiki functions

### ISSUE THREAD

**Issue by dregad** [gturri/nspages#145]
- utf8_* functions have been replaced by PhpString class methods
- resolve_pageid() is replaced by PageResolver class

**Comment by dregad** [comment]
Fixed in #144

**Comment by Autumnf0x** [comment]
Messages in DokuWiki deprecated log:
```
utf8_strtoupper() is deprecated. It was called from nspages_printerNice::_firstChar() in /var/www/dokuwiki/lib/plugins/nspages/printers/printerNice.php:81 dokuwiki\Utf8\PhpString::strtoupper() should be used instead!
utf8_substr() is deprecated. It was called from nspages_printerNice::_firstChar() in /var/www/dokuwiki/lib/plugins/nspages/printers/printerNice.php:81 dokuwiki\Utf8\PhpString::substr() should be used instead!
resolve_pageid() is deprecated. It was called from namespacePreparer::getMainPageId() in /var/www/dokuwiki/lib/plugins/nspages/fileHelper/namespacePreparer.php:44 dokuwiki\File\PageResolver should be used instead!
```

- nspages plugin version: 2023-07-11;
- DokuWiki version: 2023-04-04a "Jack Jackrum";
- PHP 8.2;

> I really hope this super plugin is still maintained.

**Comment by Miro-Collas** [comment]
> Messages in DokuWiki deprecated log:
> 
> ```
> utf8_strtoupper() is deprecated. It was called from nspages_printerNice::_firstChar() in /var/www/dokuwiki/lib/plugins/nspages/printers/printerNice.php:81 dokuwiki\Utf8\PhpString::strtoupper() should be used instead!
> utf8_substr() is deprecated. It was called from nspages_printerNice::_firstChar() in /var/www/dokuwiki/lib/plugins/nspages/printers/printerNice.php:81 dokuwiki\Utf8\PhpString::substr() should be used instead!
> resolve_pageid() is deprecated. It was called from namespacePreparer::getMainPageId() in /var/www/dokuwiki/lib/plugins/nspages/fileHelper/namespacePreparer.php:44 dokuwiki\File\PageResolver should be used instead!
> ```
> 
>     * nspages plugin version: 2023-07-11;
> 
>     * DokuWiki version: 2023-04-04a "Jack Jackrum";
> 
>     * PHP 8.2;
> 
> 
> > I really hope this super plugin is still maintained.

Confirmed, I'm seeing the same.

**Comment by popjelev** [comment]
Hello,

I've offered to help @gturri few months ago as he posted he doesn't have much time and looking for someone to help him maintain the project. Nicely he accepted :) but unfortunately I've also been very busy these past months and wasn't able to jump into the project yet :( I'll try to do so after the end of August and sorry for making excuses here - I've got an unexpected extra project and I have to be focused on it at the moment.

Regards,

**Comment by dregad** [comment]
There is a fix available for this issue, see the PR #144 I submitted a few months ago. That has not yet been merged yet, as it breaks backwards-compatibility with Hogfather / PHP 7.0 and older; see discussion in the PR for details.

I would definitely not be qualifying this plugin as unmaintained, even though not very active @gturri has always been responsive to submitted issues in the past years. Anyway great to hear that he'll be getting some help, thanks @popjelev

**Comment by gturri** [comment]
As @popjelev  says: we're busy with other projects, but this plugin is still maintained (eg: last update was a month ago).

And as @dregad says: he was kind enough to propose a fix, but I did not merge yet it because I'm afraid it seems it may break retro-compatibility for non Igor users. According to [the stats](https://www.dokuwiki.org/popularity) it means that more that 80% of dokuwikid instances would be impacted.

That being said, since Igor was released several months ago, I guess we could consider merging it soon. I'll try to take some time to look into that (ie: re-read the code, run the test suite, ...) in the next few days.

**Comment by gturri** [comment]
So, I have a good news and a news a bit less good.

The good news is that it worked flawlessly to integrate the fix of @dregad (merging worked out of the box thanks to your rebase the other day. Thanks a lot for you work on that, and for your patience :+1: ), that the test suite remained green, and that it fixes a lot of those warnings. So I could already merge it, and it's available as nspages v 2023-08-14.

The news a bit less good is that I still see some deprecation warnings so I'm afraid there is still a bit more work to do. I'll try to look at it in the next few days (so I'll re-open this issue for now)

**Comment by gturri** [comment]
and, it should be all fixed now
(I'm not sure dokuwiki plugin system would handle well having several versions for a given day so I'll leave it as 2023-08-14 . If you already updated I think you could click `Re-install` on the plugin manager in order to have this last update)

**Comment by Miro-Collas** [comment]
Thank you!  :-)

**Comment by Autumnf0x** [comment]
Thank you! I'll try to track down the remaining deprecated log messages and post them here.
