### ISSUE TITLE
-pagesInNs not working as expected in "-tree" mode

### ISSUE THREAD

**Issue by Trinity503** [gturri/nspages#151]
I use this to create a tree: 
`<nspages .:imrs-wiki -tree -r -exclude -subns -pagesInNs -h1 -textNs="">`

With -pagesInNs it should sort pages and namespaces alphabetically, or am I wrong. Unfortunatetly it first lists the namespaces and then the pages.

**Comment by fiwswe** [comment]
The [documentation](https://www.dokuwiki.org/plugin%3Anspages) says nothing about sorting for `-pagesInNs `. Why would you expect that?

Maybe you should try `-naturalOrder ` or one of the other sort options?

**Comment by gturri** [comment]
Re-reading your message I see that you use `-tree`, so my screenshot above is perhaps not relevant to your use case. Here is a screenshot of what I have with both `-tree` and `-pagesInNs`.

Here I see that, as expected with the `-tree` option, pages are displayed as leaves and subnamespaces are displayed as inner nodes.

Does that make sense? Do you observe something different on your side?

![image](https://github.com/gturri/nspages/assets/308601/66c4d29f-6d0b-45d1-977e-66c102ed15d8)

**Comment by Trinity503** [comment]
Thanks gturri for your fast answer!
Without the "-tree" option your screenshot shows the result I would expect. The pages are - as the documentation says - "among" (in between) the namespaces. 
But with the "-tree" option the pages are listed not "in between" the namespaces but "after" the namespaces. I would expect the following:
```
00-index
abc
page_2
page_3
sub
  test
subns
  a
  test
toto
  tata
test
....
``` 
Now the pages are alpahetically "in between" the namespaces. Your Sceenshot shows "Windows Explorer"-like sorting and I would expect macos-finder-sorting :-)
Other sorting options did not work.
Long fix: Change code.
Easy fix: Change the docu.

Thanks for your great plugin!

**Comment by popjelev** [comment]
Sorry to nudge in but can you please show us what's macOS finder sorting would be like?

**Comment by popjelev** [comment]
This is strange. I'm currently testing with your initial query `<nspages .:imrs-wiki -tree -r -exclude -subns -pagesInNs -h1 -textNs="">` and I find that I get namespaces like `Finder` sorting. What version of the plugin you use and what version of DokuWiki?

**Comment by gturri** [comment]
When I look at the code I'm afraid @Trinity503 is correct: The `PrinterTree::_printTree` method (https://github.com/gturri/nspages/blob/master/printers/printerTree.php#L160 ) does this:

```
        foreach($tree->children as $subTree){
            $this->_printSubTree($subTree, 1);
        }

         foreach($tree->pages as $page){
             $this->_printElement($page, 1);
       }
```

and the comment at the bottom of the file (https://github.com/gturri/nspages/blob/master/printers/printerTree.php#L206 ) makes it clear that `$tree->children`  represent sub-subnamespaces.
So, for a given subnamespace, we indeed print its pages at after the sub-subnamespaces.

**Comment by gturri** [comment]
I guess it could be possible to propose the other behavior. If we want to do that I think we should:
- add a new flag for the plugin (in order to not change the behavior for existing users who are happy with the current way it works)
- do the sort directly in the `PrinterTree::_printTree` method by merging the arrays `$children` and `$pages` and sorting this array... by passing it to ` $this->_sorter->sort` I think.
(I guess in this case we would not need to call `_orderTree` on L22 (https://github.com/gturri/nspages/blob/master/printers/printerTree.php#L22 ) then)

For the record @Trinity503 , on a scale from 1 to 10 where 10 is "you really want this feature" and 1 is "you were surprised by this behavior but do not really care", how much would you appreciate this feature? :D

**Comment by Trinity503** [comment]
DokuWiki: Release 2023-04-04a "Jack Jackrum"
nspages: 2023-07-11 (gturri-nspages-8e7a7fc)

gturri just agreed with me about the sorting. Thank you, I already thought, I'm crazy.

This is what I am seeing:
![image](https://github.com/gturri/nspages/assets/54348970/f3b9569b-6af8-4bd0-840a-d1bd94df8900)

This is what I would expect:
![image](https://github.com/gturri/nspages/assets/54348970/daa3fadc-2850-45f5-9dad-4bcef67ef574)

As you can see in the first picture "adam" is listed as namespace with a link to that page and also as a page with a link to that page (this is the same in the next picture without tree):
![image](https://github.com/gturri/nspages/assets/54348970/f0f03c84-36aa-4e6a-8d9d-0ba4c51c1426)
Is there any way to avoid this?

**Comment by popjelev** [comment]
Now I've got it with this example :D

**Comment by Trinity503** [comment]
> I guess it could be possible to propose the other behavior. If we want to do that I think we should:
> 
> * add a new flag for the plugin (in order to not change the behavior for existing users who are happy with the current way it works)
> * do the sort directly in the `PrinterTree::_printTree` method by merging the arrays `$children` and `$pages` and sorting this array... by passing it to ` $this->_sorter->sort` I think.
>   (I guess in this case we would not need to call `_orderTree` on L22 (https://github.com/gturri/nspages/blob/master/printers/printerTree.php#L22 ) then)
> 
> For the record @Trinity503 , on a scale from 1 to 10 where 10 is "you really want this feature" and 1 is "you were surprised by this behavior but do not really care", how much would you appreciate this feature? :D

Well the thing with the "double" entries is a 10 for me. The other one is a 6, which means, I would have to try to do this on my own with my limited programming skills.

**Comment by gturri** [comment]
I agree that the double entry behavior is not great.
I think it's a bit related to what dokuwiki consider to be namespace. In a nutshell: I think your page "adam" has id `adam`, but if you move it to `adam:start` then nspages will not make it appear as a page node (and dokuwiki will in both case consider that it is a namespace). I think this behavior is the same as the one described on #142 and #128 .
That reminds me that part of #140 is supposed to fix this behavior, but I'm afraid I never really had time to look thoroughly at this PR

**Comment by Trinity503** [comment]
Working like a charm! Thank you!
