### ISSUE TITLE
Uppercase Namespace Breaks listing

### ISSUE THREAD

**Issue by ajshea** [gturri/nspages#152]
When creating pages with bureaucracy plugin and the namespace path is substituted, if the data was entered in Mixed or UPPERCASE, nspages complains that the path does not exist. Making the namespace path lowercase works. 

Indexmenu, gallery, filelist and other plugins handle this "case" without complaint. 

Unfortunately, namespace replacement patterns have mechanisms for upper-case adjustment, but not lower-case.

**Comment by gturri** [comment]
Thanks for this bug report.
I'm afraid I don't know the bureaucracy plugin (yet), so I don't have clues about this issue at the moment. I'll try to look into it when I am able to dedicate some time to it.
(That being said, I must admit that I don't see myself being able to dedicate time to it any time soon :-/ )

**Comment by ajshea** [comment]
I think the issue is that nspages does not enforce lower-case on the namespace path before it attempts to enumerate the list. 

I am using bureaucracy plugin to create pages, and the namespace path added to the new page ends up with capital letters, which then don't work with nspages. Bureaucracy does not offer an option to change the case of the text that is substituted into the new page, but so far nspages is the only plugin that breaks because of this. So it seems that it must be that the namespace is not reduced to lowercase before being enumerated. 

Example: 
    <nspages :MX:HMT:equip: -textPages="Equipment Info" -exclude -exclude:equip_tpl -simpleList >

    this namespace doesn't exist: MX:HMT:equip  

The country code and project code are inserted into the new page by Bureaucracy "as is" from the data entry form.

**Comment by gturri** [comment]
Thanks for this explanation.
If I understand correctly, then the new version I just pushed (v 2022-08-22) should fix that issue.
Please let me know if it's actually the case.

**Comment by ajshea** [comment]
Yes, this fix works. Thank you!
