### ISSUE TITLE
-exclude without trailing space causes This namespace does not exist error

### ISSUE THREAD

**Issue by dregad** [gturri/nspages#153]
I have a page with a complex nstables tag that requires multiple excludes. In the interest of making it easier to read & maintain, I split it over multiple lines like so:

```
<nspages -r -title -sortByDate -reverse -numberedList -textPages="" 
  -exclude:pv:modele_pv 
  -exclude:wiki: 
  -exclude:playground: 
  ... more excludes ...
>
```

If there is no space after any of the `-exclude` lines, I get e.g.

```
this namespace doesn't exist: -exclude:pv:wiki
```

Adding a trailing space fixes the problem. I would expect the newline to be treated like the space.

**Comment by dregad** [comment]
Actually the same problem occurs after other options too

**Comment by dregad** [comment]
Looks like root cause is 1042ed49fa69b9d80dfae820a41a624f7c0751eb

**Comment by dregad** [comment]
Proposed fix in PR #154

**Comment by gturri** [comment]
thanks for the bug report!
(Don't hesitate to re-open it if it appears the last version don't fix every occurrence of it.)

**Comment by dregad** [comment]
@gturri Thanks for the fast response. I have tested your fix. 

The good news is that it does improve the situation, effectively handling the trailing `\n` scenario which was initially causing me problems, in addition to the original case with a regular space (` `). 

But of course as you suspected in https://github.com/gturri/nspages/pull/154#issuecomment-1721658046 it will fail again when the option is followed by any other kind of whitespace (e.g. `\t` or `\r`). 

Of course you can add another *str_replace()* call for each possibility, but that does not feel right. I believe that my approach of using a *preg_replace()* call was cleaner and more generic. 

The regression on the original issue #123 that my proposed fix introduced can easily be addressed by using a modified regex pattern (`\s+` instead of `\s*`). I've tested that locally and the original issue `<nspages -exclude:page1 -exclude:page10>` seems to be correctly handled.

I can't reopen this issue myself, but I'll submit another PR so you can review and test.
