### ISSUE TITLE
Surrounded by p-tag causes ugly multi-column lists using plugin wrap

### ISSUE THREAD

**Issue by erik-alm** [gturri/nspages#163]
I experience problems when combining the nspages plugin with the wrap plugin.

My wiki code:

```DokuWiki
<WRAP colsmall>
<nspages :ns1:ns2 -exclude:template -textPages="" -simpleList>
</WRAP>
```

Renders HTML like this (I think, it is possible some end tags are missing...):

```HTML
<div class="wrap_colsmall wrap__dark plugin_wrap">
  <p>
    <div class="plugin_nspages">
      <ul>…</ul>
      <div class="catpageeofidx"></div>
    </div>
  </p>
</div>
```

That extra surrounding p-tag is interpreted (by Chrome and Firefox on macOS) as an extra initial p-tag causing the first line of the first column of the list to be slightly pushed down compared to column 2 and later.

If the p-tag is required for some purpose, can it either get a class or be moved inside the plugin_nspages-div? That way it can be managed using CSS and so on.

(Though, it is possible a p-tag at this level is broken HTML and not even CSS will be able to hide it...)

**Comment by gturri** [comment]
If I understand correctly, this additional `<p>` does not come from nspages. I guess you should get in touch with the owner of the wrap plugin.
(I'll hence close this bug report, but feel free to re-open it if you believe my analysis is incorrect)
