### ISSUE TITLE
Breaking bug on latest version

### ISSUE THREAD

**Issue by bhartshorn** [gturri/nspages#170]
Hello, thanks for your effort developing this important plugin!

I just updated nspages via the the extension manager. Now there's an nspages related error message that prevents my wiki from loading:

`Fatal error: Declaration of NspagesTreeNsNode::offsetExists(mixed $offset): bool must be compatible with ArrayAccess::offsetExists($offset) in /var/www/html/lib/plugins/nspages/printers/printerTree.php on line 249`

As far as I know, this wiki is fully updated otherwise, the latest version of Kaos. No particularly weird configurations or modifications. Running in a PHP docker container. I can get more version/environment information if needed.

Edit: I'm using the following php container, with a modified php.ini to enable extra modules: `php:7-apache`

**Comment by gturri** [comment]
Thanks for this bug report.

Indeed, the latest update is meant to be compatible only with PHP 8 or above (I documented it on https://www.dokuwiki.org/plugin:nspages ; but I'm afraid there is no way to warn about it on the Dokuwiki admin panel). If you are using an older version of php then you should install nspages with this tarball: https://github.com/gturri/nspages/zipball/61857ee52e02c1f42d8dcb540aa80ba411db1485 . On the other hand please let me know if you are using PHP8, as it would mean I should have a closer look.

**Comment by bhartshorn** [comment]
> On the other hand please let me know if you are using PHP8, as it would mean I should have a closer look.

Thanks, I just looked at the dokuwiki docs and found that they recommend php 8. I updated my original post to say that I am indeed running php 7. I'll try to get php updated rather than roll back. 

I think it's useful to have a bug report for when others inevitably hit this issue. Thanks for the quick response!
