### ISSUE TITLE
nspages disregarding exclude option

### ISSUE THREAD

**Issue by gennff** [gturri/nspages#30]
hi guillaume,
 
after upgrading dokuwiki and nspages to the last versions (as of now), i experience some incompatibility with the (my) established use of nspages in that the -exclude option does no longer seem to be recognized an option at all.
 
me, i usually employ nspages like so, suppressing the default "start" page(s): <nspages -h1 -subns -r -pagesInNs -exclude:start>
 
from today on, however, i continuously get this error message: (in english from german) " This namespace does not: -exclude:start ".
 
playing around with nspages parameters (namespace and options), i conclude that somehow "-exclude" does no longer gets pased correctly. i also noticed on github that you changed nspages/optionParser.php recently... maybe some edit bug creeped in... i'm not enough a php dev to find this easily though.
 
that's it, thanks for the plugin, regards peter

**Comment by gturri** [comment]
Thank you for the bug report !

The recent refactoring indeed introduced a regression: there's a conflict in argument parsing which can be reproduced with

    <nspages -r -exclude:start>

I'll try to fix it soon. Meanwhile, you may use an older version of the plugin, for example https://github.com/gturri/nspages/zipball/4be431f26127f36f290eb8c3ab62c1720756d5e3
