### ISSUE TITLE
Output a list of the 5 newest pages

### ISSUE THREAD

**Issue by bobcanthelpyou** [gturri/nspages#31]
If the options '-nbItemsMax=5' / '-reverse -nbItemsMax=5' are used the output shows only the 5 oldest pages

But how to show the 5 newest pages?

Is it already possible and i missed some options? Or is it possible to add a new feature to make it possible?

**Comment by gturri** [comment]
It's currently not possible to sort on the age of the page. However, it seems feasible to add an option to sort on the date of the last revision.

I likely won't have the time to try to do it soon, but I'll keep this feature in mind.

**Comment by gturri** [comment]
Actually I just added the option sortByDate, which sort the page by date of last modification (it seems it's the only date we can get: Dokuwiki doesn't seem to provide eg the creation date). I hope it fits your needs.

**Comment by bobcanthelpyou** [comment]
If i use '-nbItemsMax=5' or '-reverse -nbItemsMax=5' or '-nbItemsMax=5 -sortByDate' or '-reverse -nbItemsMax=5 -sortByDate' the output is the 'same', i don't get the newest pages just the oldest. Maybe 'nbItemsMax' only show the oldest pages?

**Comment by gturri** [comment]
Indeed, nbItemMax doesn't seem to behave well with sortByDate. We're currently sorting after keeping only 5 items, which is rather dumb. Thanks for pointing it. I'm re-opening this issue.

**Comment by gturri** [comment]
I believe I fixed the issue. Could you please test https://github.com/gturri/nspages/zipball/fix31 ; and tell me if you're still experiencing problems?

**Comment by bobcanthelpyou** [comment]
It tried the latest update '2015-04-12', it seems to work smoothly, thank you very much :+1:
