### ISSUE TITLE
Blank pages on all DW after installing version 30.05.2015

### ISSUE THREAD

**Issue by dturkalj** [gturri/nspages#33]
Hello,

I try to upgrade nspages plugin to latest version and after click on Update button blank page appears!
After that when I try to access any page, I receive blank screen. When I delete nspages plugin folder in lib, DokuWiki works again. then I try to make fresh install and again blank page. I even try manual installation, but it didn't help. So I retrieve previous version from backup.

Here is list of all plugins on my Wiki:
acl, authad, authchained, authldap, authmysql, authpgsql, authplain, bookcreator, bureaucracy, cacherevisionserase, changes, ckgedit, cleanup, clearhistory, condition, config, const, csv, data, discussion, dw2pdf, dwedit, editx, extension, include, indexmenu, info, loglog, nspages, popularity, publish, revert, safefnrecode, sqlite, table2csv, tag, tagentry, testing, text, tools, toucher, translation, upgrade, usermanager, var, wrap.

**Comment by gturri** [comment]
Thank you for this bug report.

I can't reproduce this issue, so I'm going to need a little more
information:

* Do this issue appear in every page, or only on pages where the plugin is
used?
* I guess you have php errors.  I would be grateful if you could you look
in your apache logs, and copy those errors

Hello,

I try to upgrade nspages plugin to latest version and after click on Update
button blank page appears!
After that when I try to access any page, I receive blank screen. When I
delete nspages plugin folder in lib, DokuWiki works again. then I try to
make fresh install and again blank page. I even try manual installation,
but it didn't help. So I retrieve previous version from backup.

Here is list of all plugins on my Wiki:
acl, authad, authchained, authldap, authmysql, authpgsql, authplain,
bookcreator, bureaucracy, cacherevisionserase, changes, ckgedit, cleanup,
clearhistory, condition, config, const, csv, data, discussion, dw2pdf,
dwedit, editx, extension, include, indexmenu, info, loglog, nspages,
popularity, publish, revert, safefnrecode, sqlite, table2csv, tag,
tagentry, testing, text, tools, toucher, translation, upgrade, usermanager,
var, wrap.

—
Reply to this email directly or view it on GitHub
<https://github.com/gturri/nspages/issues/33>.

**Comment by dturkalj** [comment]
It happens on every page. At this moment I don't use nspages plugin on any page.
It start's just after I click update button on plugins manager. Instead of return to plugin manager with installation success message, wiki produce blank page.
And after that any page I call, I receive blank page.

As I mentioned earlier, I try to reinstall plugin manually, but it didn't help.
And, forgot to mention, my wiki is running on Windows 2003, IIS 6, PHP 5.3.14.

I will try to find errors in logs, but I need some time.

**Comment by marnar** [comment]
Same problem here, all pages blank after installing the update. Apache errorlog shows : 
PHP Parse error:  syntax error, unexpected '[' in pathtowebdir/lib/plugins/nspages/action.php on line 24

**Comment by gturri** [comment]
Thanks for this info. I guess I haven't been able to reproduce this issue because it's due to a different version of PHP. @marnar , which version are you using?

Based on the error log you reported, I tried to push a fix. I would be grateful if you could test it (version 2015-06-01), and tell me if  it works

**Comment by dturkalj** [comment]
Yes, I finnaly find PHP errors, it's the same as @marnar :
[31-May-2015 09:52:19 UTC] PHP Parse error:  syntax error, unexpected '[' in D:\Dokuwiki\lib\plugins\nspages\action.php on line 24

but your today fix has sucessfuly fix it !
Thanks!

**Comment by gturri** [comment]
Thanks for this feedback. And thanks again for the bug report: without it I wouldn't have noticed I broke the plugin on a few platforms.
