### ISSUE TITLE
-r overrules -exclude:subNs:

### ISSUE THREAD

**Issue by gturri** [gturri/nspages#49]
when using -r, then the plugin ignores exclusions (-exclude:subNs:)

**Comment by whnr** [comment]
I want to hop on this, as I see something similar. I have the structure:
`:ns0:ns1:ns2`
I am on a page named: `:ns0:ns1`and want to recursively list al the pages in the namespace with the same name `.:ns1`. But I want to exclude alle the pages in the subnamespace `:ns0:ns1:ns2:` 

So I write:
`<nspages .:ns1 -r -idAndTitle -actualTitle=3 -simpleList -exclude:ns2:>`

But this still shows everything in `ns2:`

**Comment by gturri** [comment]
To improve the traceability of the issues, please open a new bug report.
