### ISSUE TITLE
Please add an option to group pages with their namespaces when using -r

### ISSUE THREAD

**Issue by polyzen** [gturri/nspages#54]
Currently -r will cause all subnamespaces and pages to be grouped alongside those of their parents. It would be great if the hierarchy can be kept, like a tree perhaps.

**Comment by gturri** [comment]
It could indeed be an interesting id to add an option that would render the documents as a hierarchy. However, I'm not a frontend guy, and I'm afraid it would require css and html skills I don't have.
I'm leaving this issue open in case someone willing to make a pull request comes here.

**Comment by polyzen** [comment]
No longer using Doku nor this workflow. Thank you.

**Comment by gturri** [comment]
For the record (in case anyone arrives on this feature request in the future): this feature has just been added. I can be used with the -tree flag (eg : <nspages -r -subns -nopages -tree>)
