### ISSUE TITLE
incorrect version info

### ISSUE THREAD

**Issue by matuscak** [gturri/nspages#59]
Hello,

when I open extension manager in wiki I see "Update: New version 2016-07-21 is available" message. When I click on update button, I get "update successfull" message, but info about new version available is still there.

I think the problem is caused by the fact that last change in repository was on 2016-07-21, but the date written in plugin.info.txt file is 2016-07-17. Maybe this should be increased/aligned?

Thank you!

**Comment by gturri** [comment]
Indeed, it seems I forgot to update the version. It should be fixed now. Thanks for pointing it out!
