### ISSUE TITLE
Enable the use of regex to select the documents by (first) heading

### ISSUE THREAD

**Issue by vchrizz** [gturri/nspages#63]
pregPagesOff is neat to filter out pages by their id, but if you want to filter for "recent" and "outdated" pages, its unhandy to copy them to a new id, easier would be to edit heading and filter by that.

**Comment by gturri** [comment]
Indeed, it makes sense. And it shouldn't be too hard to implement.

I will likely not have the time to work on it in a near future, but I'll keep it in mind.
(OTOH, I would gladly accept a pull request, and I could give advice to implement it)

**Comment by gturri** [comment]
@vchrizz I just pushed a new version which adds the options `-pregPagesTitleOn` and `-pregPagesTitleOff`. 
I started to add the same options for namespaces, but it doesn't work yet. However, those two first options might already fit your needs.

**Comment by gturri** [comment]
I managed to implement the options for the namespaces too. Feel free to re-open this issue if you believe it doesn't actually fit your needs.
