### ISSUE TITLE
Suggestion for an additional option

### ISSUE THREAD

**Issue by diltigug** [gturri/nspages#64]
Hi, I would like to make a suggestion for an additional option for nspages:
I would like to list only one file of the subnamespaces. Specifically only the "start.txt".

Perhaps an option could be: `-subns:start` ?

I do not know if it is already possible on another way.

**Comment by gturri** [comment]
You may try `-pregPagesOn="/start/"`. Does it fit your needs?

**Comment by diltigug** [comment]
Great, taht is it, it works, thank you and greetings from munich.
