### ISSUE TITLE
remove "Pages in this namespace:"

### ISSUE THREAD

**Issue by nerdoc** [gturri/nspages#67]
Could you add an option to remove the in my case disturbing "Pages in this namespace:" header above the list? Something like `-noListTitle` or similar.

**Comment by gturri** [comment]
You may try `-textPages=""`. Eg: `<nspages -textPages="">`

Feel free to reopen this issue if it doesn't fit your needs.

**Comment by nerdoc** [comment]
This is perfect. I saw that this already is in the docs: "some text will be displayed instead of the default text, to introduce the pages list" - this was (at least for me) not completely clear - I would use the word "header", "title" or similar here to explain better what this does.
Thanks anyway.
