### ISSUE TITLE
Feature Request: Customized page ID option for sorting

### ISSUE THREAD

**Issue by tofighi** [gturri/nspages#70]
That would be great that we can add a custom ID to each page, and will sort it based on that ID. 
I mean, for each page/ns, we can add a custom tag such as <id?10>, or  <id?name> and the sorting function sorts based on that.
This way, we will have the power of giving arbitrary page order regardless of the name or original page id.

**Comment by gturri** [comment]
It indeed seems an interesting idea!
I'm afraid I won't have time to work on it any time soon, but if someone if willing to implement it I could give pointers and I would be glad to review a pull request.

**Comment by gturri** [comment]
I'm just realizing that it is now possible to do that:
- with the [meta](https://www.dokuwiki.org/plugin:meta) plugin one can add arbitrary metadata to a page. It could be used to register a sort order
- then nspages `-sortByMetadata` option can be used to sort based on this
