### ISSUE TITLE
-exclude not excluding.

### ISSUE THREAD

**Issue by KevinMaschke** [gturri/nspages#85]
Hi! I'm using your plugin to create the navigation menu and am trying to exclude a specific namespace from it.

Following the instructions, I use "-exclude:subNS" as follows:

`{{indexmenu>mvr#1|js#bj-tango.png -exclude:frontend: navbar tsort nsort max#10#10 notoc nomenu}}`

But the "FrontEnd" namespace keeps appearing in the navigation. Any idea what could be causing this?

Thanks!

**Comment by gturri** [comment]
Hi,

according to the example you're providing, it seems you're using the [indexmenu](https://www.dokuwiki.org/plugin:indexmenu) plugin and not the [nspages](https://www.dokuwiki.org/plugin:nspages) one.
You should probably report bugs about this plugin on https://github.com/samuelet/indexmenu/issues

**Comment by KevinMaschke** [comment]
Oh damn!! Sorry for that! I looked at two different things at the same time!
