### ISSUE TITLE
-r overrules -exclude:subNs:

### ISSUE THREAD

**Issue by whnr** [gturri/nspages#88]
Same as #49. New report as wished by @gturri 
I want to hop on this, as I see something similar. I have the structure:
`:ns0:ns1:ns2`
I am on a page named: `:ns0:ns1`and want to recursively list al the pages in the namespace with the same name `.:ns1`. But I want to exclude alle the pages in the subnamespace `:ns0:ns1:ns2:` 

So I write:
`<nspages .:ns1 -r -idAndTitle -actualTitle=3 -simpleList -exclude:ns2:>`

But this still shows everything in `ns2:`

**Comment by dregad** [comment]
Similar problem here...

**Comment by Phoenix616** [comment]
Any update on this? Not being able to ignore a full namespace including its subpages makes the tree functionality kinda hard to use as you have to exclude all subpages of a namespace manually and add new ones each time a new site is added just to hide it completely.

**Comment by gturri** [comment]
I'm afraid this issue got out of my mind... :-/ Also, I'm afraid I really won't have enought time to dedicate to my OSS projects in the next few month to fix this (however, if a patch is submitted, I can have a look at and merge it)

**Comment by gturri** [comment]
thanks a lot for the patch!
just one question: from a user point of view, in the case described in the 1st post, would you rather have to input `-exclude:ns2:` or `-exclude::ns0:ns1:ns2:`?
I'm thinking that if there is also a `:ns0:other_ns:ns2:`, then it wouldn't be possible to include `:ns0:other_ns:ns2:` and to include `:ns0:ns1:ns2:` at the same time.
What do you think?

**Comment by Phoenix616** [comment]
I feel like the basic exclude option should just match any part of the path and that more complex rules would ideally be handled by a regex matcher for the full path like requested in #5.

**Comment by gturri** [comment]
TFW a user of my code has a better knowledge than me of the bugtracker ^^

Thanks a lot for the patch. Merged! :)
