### ISSUE TITLE
Feature idea: display first sentence instead of title or h1?

### ISSUE THREAD

**Issue by TheDavidJohnson** [gturri/nspages#96]
First: **thank you** for a fantastic plugin! I love it!

Since it's possible (and useful!) to be able to display the first H1 found on a page, is it similarly possible to display the first sentence? (Up to the first line break or first "." character, perhaps?)

**Comment by gturri** [comment]
Thanks for this feedback.

The title is taken from the metadata of the page. The available metadata is shown on https://www.dokuwiki.org/devel:metadata . I see that there's an `abstract` entry, which should be `aw text abstract (250 to 500 chars) of the page`. Looks like it could be more or less what you're looking for. It would be worth looking into it.

**Comment by TheDavidJohnson** [comment]
Excellent! Thanks so much for the response. I'll take a look!

**Comment by gturri** [comment]
I gave it a try: I added the `-abstract` option on this draft: https://github.com/gturri/nspages/zipball/dev_96 . This option takes the `abstract` metadata and displays it instead of the page title. I would be grateful if you can give this draft a try and tell me if it matches what you had in mind.

**Comment by gturri** [comment]
no feedback for almost 2 years => I'm closing the issue.
If someone is still interested in this feature, feel free to test the version above, and to reopen this issue afterwards
