### ISSUE TITLE
Indented Subnamespaces in SimpleList

### ISSUE THREAD

**Issue by degers** [gturri/nspages#97]
Is there a way to indent the Subnamespaces, when they're part of the list? Can't see a class or element to put some CSS on it.

Usage: 
<nspages  -r=2 -simpleList  -h1  -textPages="">

**Comment by gturri** [comment]
(Sorry for the delay before this reply)

I'm afraid there's currently no way to do it. If you believe adding a CSS class for simpleList might be useful, then, please, don't hesitate to submit a pull request.  (the code responsible for displaying the simpleList is this simple class: https://github.com/gturri/nspages/blob/master/printers/printerSimpleList.php )
